// Generated by https://pagedraw.io/pages/9009
import Tab_default from './tab_default';
import Tab_selected from './tab_selected';
import Submittableinput from './submittableinput';
import Rating from './rating';
import React from 'react';
import './landingpage.css';

function render() {
    return <div className="landingpage-landingpage-4">
        <div className="landingpage-0">
            <div className="landingpage-rectangle-1">
                <div className="landingpage-0-0-0">
                    <div className="landingpage-path-1">
                        <div className="landingpage-0-0-0-0-0">
                            <div className="landingpage-0-0-0-0-0-0">
                                <div className="landingpage-0-0-0-0-0-0-0">
                                    <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/8126710621713976-1522030851726-63A58C9A-313A-4281-ADCB-6CF402BC5A7F.png" className="landingpage-local_movies_-_material-8" /> 
                                </div>
                            </div>
                            <div className="landingpage-movietime-6">Movietime</div>
                        </div>
                        <div className="landingpage-0-0-0-0-1">
                            <div className="landingpage-tab_default-1">
                                <Tab_default /> 
                            </div>
                        </div>
                        <div className="landingpage-0-0-0-0-2">
                            <div className="landingpage-tab_selected-1">
                                <Tab_selected /> 
                            </div>
                        </div>
                        <div className="landingpage-0-0-0-0-3">
                            <div className="landingpage-tab_default-16">
                                <Tab_default /> 
                            </div>
                        </div>
                    </div>
                    <div className="landingpage-0-0-0-1">
                        <div className="landingpage-0-0-0-1-0">
                            <div className="landingpage-the_lion_king-2">
                                The Lion King
                            </div>
                        </div>
                        <div className="landingpage-0-0-0-1-1">
                            <div className="landingpage-19">1994 </div>
                        </div>
                        <div className="landingpage-0-0-0-1-2">
                            <div className="landingpage-path-7" /> 
                        </div>
                        <div className="landingpage-0-0-0-1-3">
                            <div className="landingpage-a_lion_cub_crown_pri-1">
                                {"A Lion cub crown prince is tricked by a treacherous uncle into thinking he caused his father's death and flees into exile in despair, only to learn in adulthood his identity and his responsibilities."}
                            </div>
                        </div>
                        <div className="landingpage-0-0-0-1-4">
                            <div className="landingpage-directors_-5">
                                {"Directors:"}
                            </div>
                            <div className="landingpage-roger_allers_rob_mi-4">
                                {"Roger Allers, Rob Minkoff"}
                            </div>
                        </div>
                        <div className="landingpage-0-0-0-1-5">
                            <div className="landingpage-write_a_comment-1">
                                Write a comment
                            </div>
                        </div>
                        <div className="landingpage-0-0-0-1-6">
                            <div className="landingpage-path-4">
                                <div className="landingpage-0-0-0-1-6-0-0">
                                    <div className="landingpage-i_posted_a_comment_a-1">
                                        I posted a comment about the movie
                                    </div>
                                </div>
                                <div className="landingpage-0-0-0-1-6-0-1">
                                    <div className="landingpage-path-5" /> 
                                </div>
                                <div className="landingpage-0-0-0-1-6-0-2">
                                    <div className="landingpage-submittableinput-2">
                                        <Submittableinput /> 
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div className="landingpage-0-0-0-2">
                        <div className="landingpage-0-0-0-2-0">
                            <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1690659870937336-1522030851835-0908FF5F-B6FA-4260-92A5-0F8688D1BD8A.png" className="landingpage-bitmap-1" /> 
                        </div>
                        <div className="landingpage-0-0-0-2-1">
                            <div className="landingpage-what_did_you_think_-1">
                                {"What did you think?"}
                            </div>
                        </div>
                        <div className="landingpage-0-0-0-2-2">
                            <div className="landingpage-path-48">
                                <div className="landingpage-0-0-0-2-2-0-0">
                                    <div className="landingpage-rating-3"><Rating /> </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div className="landingpage-1" /> 
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}