// Generated by https://pagedraw.io/pages/9009
import Stardefault from './stardefault';
import Starempty from './starempty';
import Starfilled from './starfilled';
import React from 'react';
import './rating.css';

function render() {
    return <div className="rating-rating-3">
        <div className="rating-0">
            <div className="rating-0-0">
                <div className="rating-0-0-0">
                    <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/4795570182381435-1522030851378-12FF93FD-9981-44C4-ABF8-88E2E7E4F180.png" className="rating-star_d_copy-4" /> 
                </div>
            </div>
            <div className="rating-star_default-1">
                <Stardefault /> 
            </div>
            <div className="rating-star_empty-1"><Starempty /> </div>
            <div className="rating-star_filled-8"><Starfilled /> </div>
            <div className="rating-0-4">
                <div className="rating-0-4-0">
                    <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/6541037798577595-1522030851669-0A569666-47DF-4ADB-8B02-688260B9B6B2.png" className="rating-star_d-6" /> 
                </div>
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}