// Generated by https://pagedraw.io/pages/9009
import React from 'react';
import './stardefault.css';

function render() {
    return <div className="stardefault-stardefault-6">
        <div className="stardefault-0">
            <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1020245490837974-1522030851576-AF44CED6-F298-43B1-934B-780B803788AB.png" className="stardefault-star_-_material-1" /> 
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}