// Generated by https://pagedraw.io/pages/9009
import React from 'react';
import './starfilled.css';

function render() {
    return <div className="starfilled-starfilled-3">
        <div className="starfilled-0">
            <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/2502252748025969-1522030851542-083433D1-8743-4914-B9B6-4BB3D21CD383.png" className="starfilled-star_d-2" /> 
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}