// Generated by https://pagedraw.io/pages/9009
import React from 'react';
import './starempty.css';

function render() {
    return <div className="starempty-starempty-8">
        <div className="starempty-0">
            <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/8597227200794478-1522030851595-3EBBFA9A-B2B0-4A32-BE2B-14F4394BAAF9.png" className="starempty-star_d-8" /> 
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}