// Generated by https://pagedraw.io/pages/9009
import React from 'react';
import './submittableinput.css';

function render() {
    return <div className="submittableinput-submittableinput-1">
        <div className="submittableinput-0">
            <div className="submittableinput-0-0">
                <div className="submittableinput-0-0-0">
                    <div className="submittableinput-path-1">
                        <div className="submittableinput-0-0-0-0-0">
                            <div className="submittableinput-your_comment-4">
                                Your comment
                            </div>
                        </div>
                    </div>
                </div>
                <div className="submittableinput-0-0-1">
                    <div className="submittableinput-path-10" /> 
                </div>
            </div>
            <div className="submittableinput-0-1">
                <div className="submittableinput-0-1-0">
                    <div className="submittableinput-oval-1">
                        <div className="submittableinput-0-1-0-0-0">
                            <div className="submittableinput-_-9">{"+"}</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}