// Generated by https://pagedraw.io/pages/9009
import React from 'react';
import './tab_default.css';

function render() {
    return <div className="tab_default-tab_default-1">
        <div className="tab_default-0">
            <div className="tab_default-path-1">
                <div className="tab_default-0-0-0">
                    <div className="tab_default-new-1">NEW</div>
                </div>
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}