// Generated by https://pagedraw.io/pages/9009
import React from 'react';
import './tab_selected.css';

function render() {
    return <div className="tab_selected-tab_selected-1">
        <div className="tab_selected-0">
            <div className="tab_selected-path-1">
                <div className="tab_selected-0-0-0">
                    <div className="tab_selected-path-6" /> 
                    <div className="tab_selected-0-0-0-1">
                        <div className="tab_selected-0-0-0-1-0">
                            <div className="tab_selected-popular-4">POPULAR</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}